### PR TITLE
Allow audio/video sync to be configured, default to off

### PR DESCRIPTION
**Pull request by loganmc10**
The motivations for this is two-fold:

- Primarily the issue is performance, having this "second speed limiter" can hinder performance. Without better coordination between this limiter and the core limiter, bad things happen.
- Secondly, some games (recently came across World Driver Championship and Stunt Racer) don't work properly with this limiter enabled.

I'm open to the idea of having it enabled by default (though I'd rather have it disabled by default, which is what Project64 does BTW), but either way it should be configurable.

### CODE REVIEW

**Comment by Papermanzero** [comment]
I did some tests with the new Audio Plugin and Majoras Mask.

Majoras Mask should have 17 FPS in the PAL and 20 FPS in the NTSC Version.
With the old Audio Plugin I have 15 FPS(sometimes 13 FPS) in the PAL and 18FPS (sometimes 15 FPS) in the NTSC.
With the new Audio Plugin (Sync deactivated) it jumps between 15 FPS and 17 FPS in the PAL (seems ok). In the NTSC bewtween 18FPS and 20 FPS (seems also ok).

So this change is definitely useful for performance.

**Comment by Papermanzero** [comment]
@bsmiles32 
Can u maybe support?

**Comment by loganmc10** [comment]
The only real risk with de-syncing the audio like this is that the audio could fall behind.

The solution now is to pause the emulator to allow the audio to catch up, which is what causes the performance issues.

@Papermanzero I re-wrote this plugin in a different way here: https://github.com/m64p/mupen64plus-audio-sdl2

That version makes use of a new SDL API function, SDL_QueueAudio, instead of using the callback function that this plugin uses. So it just queues up the audio as soon as it receives it from the emulator.

If the queue gets too large (the audio is falling behind), it just skips some of the audio to catch up. This is almost imperceivable, plus it happens very rarely. I think this is a better solution than pausing the emulator.

You can get a binary copy of that audio plugin from here if you want to try it out http://m64p.s3-website-us-east-1.amazonaws.com/201705/

**Comment by Papermanzero** [comment]
But in this version you disabled the option For audio sync.

**Comment by loganmc10** [comment]
That version always keeps the audio in sync (within a certain tolerance), and it does so without harming the performance of the emulator.

**Comment by bsmiles32** [comment]
Merging this as it improve the situation for some people. Deeper work is needed to better coordinate core and audio plugin.

**Pull request merged**
